# what is numpy
    array 
    list 
    installation
    import
    

In [2]:
# to install numpy

In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: C:\Users\Krunal\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [5]:
# import numpy 
# as is alias we give then as shot name 


In [6]:
import numpy as np

In [7]:
# IT means that we did not want to write numpy every time now onward we can use np istad of numpy

In [11]:
# creating array 
x = np.array([1,2,3,4,5])
print (x)
print (type(x))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
# creating List
y = [1,2,3,4,5]
print (y)
print (type(y))

[1, 2, 3, 4, 5]
<class 'list'>


# difference of list and Array
    data type torage 
        array : we can use only same type of data 
        list : we can store data in any formate or data type 

In [14]:
a=np.array([1,2,3,'Krunal'])

In [15]:
a

array(['1', '2', '3', 'Krunal'], dtype='<U11')

In [16]:
# i enter number and string but it take as only string and convert that

In [17]:
l = ['Krunal', 1,2.2]
print (l)

['Krunal', 1, 2.2]


In [18]:
# in list wer can store any type of data 

    importing modele
        list : we did not want to import any module in list 
        array : we have to import first numpy module

    Numerical Operation 
        array : it does faster operation compare to list
              : it haple in machine learning 

    Modification 
        list : faster modification it have larger set of operation

    consume less memory 
        array : it is consume less amemory

In [26]:
#calculate time 
%timeit [j**4 for j in range(1,9)]

1.83 µs ± 90 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [27]:
%timeit np.arange(1,9)**4

1.69 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# cearte array 

In [29]:
l = [1,2,3,4,5,6]

print (l)
print (type(l))

a = np.array(l)
print (a)
print (type(a))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [32]:
# user input array
l=[]
print ("please enter number of element do you want to store")
n= int (input())

for i in range(1,n+1):
    element = input("enter : ")
    l.append(element)
print (np.array(l))
print (type(np.array(l)))


please enter number of element do you want to store


 3
enter :  1
enter :  2
enter :  32


['1' '2' '32']
<class 'numpy.ndarray'>


In [34]:
# here one problum accuar every elements in string 
        # because in python user input is in string 

In [35]:
# user input array
l=[]
print ("please enter number of element do you want to store")
n= int (input())

for i in range(1,n+1):
    element = int(input("enter : "))
    # we did type casting here so we convert string into int
    l.append(element)
print (np.array(l))
print (type(np.array(l)))


please enter number of element do you want to store


 3
enter :  1
enter :  2
enter :  3


[1 2 3]
<class 'numpy.ndarray'>


In [36]:
# print dimention of array 

In [39]:
l = [1,2,3,4,5,6]

print (l)
print (type(l))

a = np.array(l)
print (a)
print (type(a))
print (a.ndim) # it is one dimention


[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [43]:
# make two dimention array 

a2 = np.array([[1,2,3],[5,6,7]])
print (a2)
print (a2.ndim)

[[1 2 3]
 [5 6 7]]
2


In [48]:
# make three dimenton array
a3 = np.array ([[[1,2,3],[5,6,3],[7,8,9]]])
print (a3)
print (a3.ndim)

[[[1 2 3]
  [5 6 3]
  [7 8 9]]]
3


In [51]:
# make n dimantion array 
an = np.array ([55,56,57,58],ndmin=20)
print (an)
print (an.ndim)

[[[[[[[[[[[[[[[[[[[[55 56 57 58]]]]]]]]]]]]]]]]]]]]
20


# create special type of array 

1. make array with all zero 
    

In [55]:
a_zero = np.zeros(5) # 5 is element number
print (a_zero)
print (a_zero.ndim)

[0. 0. 0. 0. 0.]
1


In [56]:
a2_zero = np.zeros((3,4)) # 5 is element number
print (a2_zero)
print (a2_zero.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


2. make array with all ONE 
    

In [57]:
a_one = np.ones(5) # 5 is element number
print (a_one)
print (a_one.ndim)

[1. 1. 1. 1. 1.]
1


In [58]:
a2_one = np.ones((3,4)) # 5 is element number
print (a2_one)
print (a2_one.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


3. make array with empty

In [61]:
a_empty=np.empty(5)
print(a_empty)

[1. 1. 1. 1. 1.]


4. make array with range function

In [62]:
a_range = np.arange (4)
print (a_range)

[0 1 2 3]


5. make array with identity matrics

In [64]:
a_diagonal = np.eye(5)
print (a_diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [66]:
a_diagonal = np.eye(3,5)
print (a_diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


6. make array with line space function

a_linspace = np.linspace(0,20,num=5)
print (a_linspace)

# create Numpy Arrays with Random Number

1. rand() -- create random value between 0 and 1

In [70]:
a_rand = np.random.rand(5)
print (a_rand)

[0.97047036 0.89731484 0.294072   0.91725537 0.67302086]


In [71]:
a_rand = np.random.rand(5)
print (a_rand)

[0.23749297 0.77155743 0.70781197 0.93882465 0.97791702]


2. randn() -- create random value near to 0 and also it include nagetive value 

In [74]:
a_randn = np.random.randn(5)
print (a_randn)

[ 1.2223993  -0.07453104  0.65709358 -0.00231849 -1.28256124]


3. ranf() -- create random value in inter val [0,1)

In [78]:
a_ranf = np.random.ranf(5)
print (a_ranf)

[0.90443702 0.79924747 0.99018531 0.64769007 0.17059424]


3. randit() -- create random value between our range

In [81]:
# a_randint = np.random.randint(min,max,total_value)
a_randint = np.random.randint(5,10,10)
print (a_randint)

[7 8 6 7 6 7 9 5 7 7]


# Arithmatic Operation in array

In [82]:
a_ari = np.array([1,2,3,4,5])
a_ari_add = a_ari + 3
print(a_ari_add)

[4 5 6 7 8]


In [83]:
a1_ari = np.array([1,2,3,4,5])
a2_ari = np.array([6,7,8,9,10])

ari_add = a1_ari + a2_ari

print (ari_add)

[ 7  9 11 13 15]


In [84]:
as_ari = np.array([1,2,3,4,5])
as_ari_sub = a_ari - 3
print(as_ari_sub)

[-2 -1  0  1  2]


# function 
    1. min()
    2. max()
    3. sqrt ()

In [110]:
a = np.array([1,2,3,5,4,7,8,9,6,3,2,5,10,0])

In [111]:
print ('min : ',np.min(a))

0


In [113]:
print ('min position : ',np.argmin(a))

min position :  13


In [112]:
print ('max : ',np.max(a))

10


In [114]:
print ('max position : ',np.argmax(a))

max position :  12


In [115]:
a2 = np.array ([[2,1,4,5,6],[4,8,9,6,3]])

In [118]:
# axis 0 --> column
# axis 1 --> row

print (a2)

[[2 1 4 5 6]
 [4 8 9 6 3]]


In [117]:
print ('min : ',np.min(a2,axis=0))

min :  [2 1 4 5 3]


In [120]:
print ('min position : ',np.argmin(a2,axis=0))

min position :  [0 0 0 0 1]


print ('min : ',np.min(a2,axis=1))

In [122]:
print ('min position : ',np.argmax(a2,axis=1))

min position :  [4 2]


In [125]:
print ('sqrt :', np.sqrt(a))

sqrt : [1.         1.41421356 1.73205081 2.23606798 2.         2.64575131
 2.82842712 3.         2.44948974 1.73205081 1.41421356 2.23606798
 3.16227766 0.        ]


In [126]:
a3 = np.array ([1,2,3])
print ('sin value is :',np.sin(a3))
print ('cos value is :',np.cos(a3))

sin value is : [0.84147098 0.90929743 0.14112001]
cos value is : [ 0.54030231 -0.41614684 -0.9899925 ]


In [129]:
# cumsum
a4 = np.array ([1,2,3,6,10])

print('cumsum value is :',np.cumsum(a4))

cumsum value is : [ 1  3  6 12 22]


# shuffle 

In [254]:
a_shuf = np.array([1,2,3,4,5,6])
np.random.shuffle(a_shuf)
print (a_shuf)

[1 6 3 2 4 5]


# Unique

In [255]:
a_uni = np.array([1,2,3,4,5,6,2,5,8,2,5,4,6,2,4,6])
uni=np.unique (a_uni)
print (uni)

[1 2 3 4 5 6 8]


In [256]:
a_uni = np.array([1,2,3,4,5,6,2,5,8,2,5,4,6,2,4,6])
uni=np.unique (a_uni,return_index=True)
print (uni)

(array([1, 2, 3, 4, 5, 6, 8]), array([0, 1, 2, 3, 4, 5, 8], dtype=int64))


In [258]:
a_uni = np.array([1,2,3,4,5,6,2,5,8,2,5,4,6,2,4,6])
uni=np.unique (a_uni,return_counts=True)
print (uni)

(array([1, 2, 3, 4, 5, 6, 8]), array([1, 4, 1, 3, 3, 3, 1], dtype=int64))


a_uni = np.array([1,2,3,4,5,6,2,5,8,2,5,4,6,2,4,6])
uni=np.unique (a_uni,return_inverse=True)
print (uni)

# flatten

In [261]:
a_flat = np.array([[1,2,5,6],[8,9,7,6]])
print (a_flat)

[[1 2 5 6]
 [8 9 7 6]]


In [262]:
print (a_flat.flatten(order='F'))

[1 8 2 9 5 7 6 6]


In [263]:
print (a_flat.flatten(order='C')) # by default


[1 2 5 6 8 9 7 6]


# ravel

In [266]:
print (a_flat.ravel(order='C')) # by default

[1 2 5 6 8 9 7 6]


In [267]:
print (a_flat.ravel(order='F')) 

[1 8 2 9 5 7 6 6]


In [269]:
print (a_flat.ravel(order='A'))

[1 2 5 6 8 9 7 6]


shape in matrix 

In [132]:
a_shap = np.array ([[0,1,2,3],[8,9,4,5]])
print (a_shap)
print ()
print (a_shap.shape)

[[0 1 2 3]
 [8 9 4 5]]

(2, 4)


In [134]:
a1_shap = np.array([1,2,5,4,8],ndmin=5)
print (a1_shap)
print ()
print (a1_shap.shape)

[[[[[1 2 5 4 8]]]]]

(1, 1, 1, 1, 5)


# reshape

In [141]:
a_shap = np.array ([[0,1,2,3],[8,9,4,5]])
print (a_shap)
print ()
print (a_shap.shape)

a_reshap = a_shap.reshape(1,8)
print (a_reshap)
print ()
print (a_reshap.shape)


[[0 1 2 3]
 [8 9 4 5]]

(2, 4)
[[0 1 2 3 8 9 4 5]]

(1, 8)


# INDEXING IN NUMPY

In [144]:
a_ind = np.array ([1,2,3,4,5])

print(a_ind[-1])
print (a_ind[2])

5
3


In [155]:
a2_ind = np.array ([[1,2,3],[4,5,6]])
print ('dimantion:' ,a2_ind.ndim)
print (a2_ind)
print ()
print (a2_ind[1,1])

dimantion: 2
[[1 2 3]
 [4 5 6]]

5


In [156]:
a3_ind = np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print ('dimantion:' ,a3_ind.ndim)
print (a3_ind)
print ()
print (a3_ind[0,1,2])

dimantion: 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

6


# slicing

for perform slicing follow given formula 

x[starting:ending:step]

In [161]:
a_sli = np.array([1,2,3,4,5,6,7,8,9,10])
print (a_sli)

[ 1  2  3  4  5  6  7  8  9 10]


In [162]:
# 0  1  2  3  4  5  6  7  8  9  -- INDEXING

In [160]:
print (a_sli[2:8])

[3 4 5 6 7 8]


In [163]:
print (a_sli[:8])

[1 2 3 4 5 6 7 8]


In [164]:
print (a_sli[5:])

[ 6  7  8  9 10]


In [165]:
print (a_sli[1:8:2])

[2 4 6 8]


In [166]:
print (a_sli[1::2])


[ 2  4  6  8 10]


In [167]:
print (a_sli[:8:2])

[1 3 5 7]


print (a_sli[::2])


In [169]:
print (a_sli[::])


[ 1  2  3  4  5  6  7  8  9 10]


# iteration in numpy 

In [179]:
a_ite = np.array([1,2,3,4,55,6,7,8,9])
print (a_ite)

[ 1  2  3  4 55  6  7  8  9]


In [180]:
for i in a_ite:
    print (i)

1
2
3
4
55
6
7
8
9


In [181]:
a2_ite = np.array([[1,2,3,4,55,6,7,8,9],[11,12,13,14,15,16,17,18,19]])
print (a2_ite)

[[ 1  2  3  4 55  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


In [187]:
for i in a2_ite:
    print (i)

print ("                   ")

for i in a2_ite:
    for j in i:
        print(j)
    print ()

[ 1  2  3  4 55  6  7  8  9]
[11 12 13 14 15 16 17 18 19]
                   
1
2
3
4
55
6
7
8
9

11
12
13
14
15
16
17
18
19



In [189]:
a3_ite = np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (a3_ite)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [190]:
for i in a3_ite:
    for j in i:
        for k in j:
            print (k)
        print("========")
    print("*******")


1
2
3
4
5
6
*******
7
8
9
10
11
12
*******


In [191]:
# using function 


# nditer()

In [192]:
a3_ite = np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (a3_ite)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [194]:
for i in np.nditer(a3_ite):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [197]:
for i in np.nditer(a3_ite,flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


# ndenumerate()

In [201]:
a3_ite

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [199]:
for i,d in np.ndenumerate(a3_ite):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


# join and spilt of array

1. join

In [205]:
a11_j = np.array ([1,2,3,4])
a12_j = np. array ([4,5,6,7])
print (a11_j)
print ()
print (a12_j)


# using concatenate function 

print ( 'new array is this :')

a13_j = np.concatenate(a11_j,a12_j) # give error becaus noe we have to put two (())
print (a13_j)


[1 2 3 4]

[4 5 6 7]
new array is this :


TypeError: only integer scalar arrays can be converted to a scalar index

In [206]:
a11_j = np.array ([1,2,3,4])
a12_j = np. array ([4,5,6,7])
print (a11_j)
print ()
print (a12_j)


# using concatenate function 

print ( 'new array is this :')

a13_j = np.concatenate((a11_j,a12_j))
print (a13_j)


[1 2 3 4]

[4 5 6 7]
new array is this :
[1 2 3 4 4 5 6 7]


In [208]:
a21_j = np.array ([[1,2,3,4],[11,12,13,14]])
a22_j = np. array ([[4,5,6,7],[14,15,16,17]])
print (a21_j)
print ()
print (a22_j)


# using concatenate function 

print ( 'new 2d array is this :')
print ()
a23_j = np.concatenate((a21_j,a22_j))
print (a23_j)


[[ 1  2  3  4]
 [11 12 13 14]]

[[ 4  5  6  7]
 [14 15 16 17]]
new 2d array is this :

[[ 1  2  3  4]
 [11 12 13 14]
 [ 4  5  6  7]
 [14 15 16 17]]


In [211]:
a21_j = np.array ([[1,2,3,4],[11,12,13,14]])
a22_j = np. array ([[4,5,6,7],[14,15,16,17]])
print (a21_j)
print ()
print (a22_j)


# using concatenate function 

print ( 'new 2d array is this :')
print ()
a23_j = np.concatenate((a21_j,a22_j),axis = 0)
print (a23_j)
print ()
print ()
print ( 'new 2d array is this :')
print ()
a23_j = np.concatenate((a21_j,a22_j),axis = 1)
print (a23_j)

[[ 1  2  3  4]
 [11 12 13 14]]

[[ 4  5  6  7]
 [14 15 16 17]]
new 2d array is this :

[[ 1  2  3  4]
 [11 12 13 14]
 [ 4  5  6  7]
 [14 15 16 17]]


new 2d array is this :

[[ 1  2  3  4  4  5  6  7]
 [11 12 13 14 14 15 16 17]]


 2. stack

In [214]:
a11_s = np.array ([1,2,3,4])
a12_s = np. array ([4,5,6,7])
print (a11_s)
print ()
print (a12_s)


# using concatenate function 

print ( 'new array is this :')

a13_s = np.stack((a11_s,a12_s),axis = 0)
print (a13_s)
print ()
print ( 'new array is this :')

a13_s = np.stack((a11_s,a12_s),axis = 1)
print (a13_s)

[1 2 3 4]

[4 5 6 7]
new array is this :
[[1 2 3 4]
 [4 5 6 7]]

new array is this :
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [215]:
a13_s = np.hstack((a11_s,a12_s))
print (a13_s)

[1 2 3 4 4 5 6 7]


In [216]:
a13_s = np.vstack((a11_s,a12_s))
print (a13_s)

[[1 2 3 4]
 [4 5 6 7]]


In [217]:
a13_s = np.dstack((a11_s,a12_s))
print (a13_s)

[[[1 4]
  [2 5]
  [3 6]
  [4 7]]]


# split the array

In [219]:
a_split = np.array ([1,2,3,4,5,6,7,8])
print (a_split)


[1 2 3 4 5 6 7 8]


In [222]:
as_split = np.array_split(a_split,5)N
print (as_split)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]


In [223]:
a1_split = np.array ([[1,2,3,4],[11,12,13,14]])
print (a1_split)

[[ 1  2  3  4]
 [11 12 13 14]]


In [226]:
as1_split = np.array_split(a1_split,5)
print (as1_split)


[array([[1, 2, 3, 4]]), array([[11, 12, 13, 14]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


  # function like -- search , sort , filter

1. search

In [229]:
a_search = np.array ([1,2,34,5,6,5,7,4,2,1,36,1,5,9])
print (a_search)

[ 1  2 34  5  6  5  7  4  2  1 36  1  5  9]


In [ ]:
# 0  1  2  3  4  5  6  7  8  9 10 11  12  13 

In [230]:
pointer = np.where(a_search == 1)
print (pointer)

(array([ 0,  9, 11], dtype=int64),)


In [234]:
pointer1 = np.where((a_search%2) == 0)
print (pointer1)

(array([ 1,  2,  4,  7,  8, 10], dtype=int64),)


2. search sort array

In [236]:
a_ss = np.array([1,2,3,6,7,9])
print (a_ss)

[1 2 3 6 7 9]


In [238]:
#0 1 2 3 4 5 
x1 = np.searchsorted(a_ss,5)
print (x1)

3


In [241]:
#0 1 2 3 4 5 
x2 = np.searchsorted(a_ss,8,side='Right')
print (x2)

5


# sort the array

In [242]:
a_sort = np.array([1,8,9,4,6,5,7,3,2])
print (a_sort)

[1 8 9 4 6 5 7 3 2]


In [243]:
print (np.sort(a_sort))

[1 2 3 4 5 6 7 8 9]


In [244]:
a1_sort = np.array(['a','g','t','k'])
print (a1_sort)

['a' 'g' 't' 'k']


In [245]:
print (np.sort(a1_sort))

['a' 'g' 'k' 't']


# filter in array

In [250]:
a_filter = np.array([1,88,99,44,55,66,15])
print (a_filter)

[ 1 88 99 44 55 66 15]


In [251]:
temp = [True,False,True,True,False,False,True]
print (temp)

[True, False, True, True, False, False, True]


In [253]:
a_filter_ans = a_filter[temp]
print (a_filter_ans)

[ 1 99 44 15]


# insert in array

In [270]:
a_insert = np.array([1,2,5,6])
print (a_insert)

[1 2 5 6]


In [272]:
inter = np.insert (a_insert,3,5555)

print (inter)

[   1    2    5 5555    6]


In [274]:
inter = np.insert (a_insert,(0,4),66)

print (inter)

[66  1  2  5  6 66]


# Matrix in Numpy

In [275]:
a_mat = np.matrix ([[1,2,3],[4,5,6]])
print (a_mat)
print (type(a_mat))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [276]:
a1_mat = np.matrix ([[11,12,13],[14,15,16]])
print (a1_mat)
print (type(a1_mat))

[[11 12 13]
 [14 15 16]]
<class 'numpy.matrix'>


In [278]:
print (a_mat*a1_mat) # it give error becase in matrix one  condition must be satisfy 
# which is if mat-1 's dimantion is i*j 
# mat - 2 's dimantion is m*n
# than m and j must me same and our new matrix dimantion is i*n

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [279]:
a11_mat = np.matrix ([[11,12,13],[14,15,16],[24,25,26]])
print (a11_mat)
print (type(a11_mat))

[[11 12 13]
 [14 15 16]
 [24 25 26]]
<class 'numpy.matrix'>


In [282]:
print (a_mat*a11_mat) # a_mat -- 2*3
                     #  a11 _mat -- 3*3 
                    #  out put is 2*3 and conditon is satisfy of j = m

[[111 117 123]
 [258 273 288]]


# function in matrix

1. Transposse

In [283]:
a11_tra = np.matrix ([[11,12,13],[14,15,16],[24,25,26]])
print (a11_tra)
print (type(a11_tra))

[[11 12 13]
 [14 15 16]
 [24 25 26]]
<class 'numpy.matrix'>


In [284]:
print (np.transpose(a11_mat))

[[11 14 24]
 [12 15 25]
 [13 16 26]]


In [285]:
print (a11_mat.T)

[[11 14 24]
 [12 15 25]
 [13 16 26]]


2. swapaxes 

In [287]:
print (np.swapaxes (a11_mat,0,1))

[[11 14 24]
 [12 15 25]
 [13 16 26]]


In [288]:
print (a11_tra)

[[11 12 13]
 [14 15 16]
 [24 25 26]]


3. inverse of matrix

In [295]:
a_in = np.matrix([[4,1],[16,32]])
print (a_in)

[[ 4  1]
 [16 32]]


In [296]:
print (np.linalg.inv(a_in))

[[ 0.28571429 -0.00892857]
 [-0.14285714  0.03571429]]


4. Power

In [297]:
a_powe = np.linalg.matrix_power(a_in,2)
print (a_powe)

[[  32   36]
 [ 576 1040]]


5. rank

In [299]:
a_rank = np.linalg.matrix_rank(a_in,2)
print (a_rank)

2


6. determinate 

In [301]:
a_deter = np.linalg.det(a_in)
print (a_deter)

111.99999999999996
